// Have indicators of literal meaning and intended meaning and indicators to differentiate similarities
const answers = {
    numbers: [
        { ch: '〇', en: 'zero', }, 
        { ch: '一', en: 'one',  }, 
        { ch: '二', en: 'two', }, 
        { ch: '三', en: 'three', }, 
        { ch: '四', en: 'four', }, 
        { ch: '五', en: 'five', }, 
        { ch: '六', en: 'six', }, 
        { ch: '七', en: 'seven', }, 
        { ch: '八', en: 'eight', }, 
        { ch: '九', en: 'nine', }, 
        { ch: '十一', en: 'eleven', },
        { ch: '十二', en: 'twelve', },
        { ch: '十三', en: 'thirteen', },
        { ch: '十四', en: 'fourteen', },
        { ch: '十五', en: 'fifteen', },
        { ch: '十六', en: 'sixteen', },
        { ch: '十七', en: 'seventeen', },
        { ch: '十八', en: 'eighteen', },
        { ch: '十九', en: 'nineteen', },
        { ch: '二十', en: 'twenty', },
        { ch: '三十', en: 'thirty', },
        { ch: '四十', en: 'forty', },
        { ch: '五十', en: 'fifty', },
        { ch: '六十', en: 'sixty', },
        { ch: '七十', en: 'seventy', },
        { ch: '八十', en: 'eighty', },
        { ch: '九十', en: 'ninety', },
        { ch: '百', en: 'hundred', }, 
        { ch: '一百', en: 'one hundred', }, 
        { ch: '千', en: 'thousand', }, 
        { ch: '一千', en: 'one thousand', }, 
        { ch: '万/一万', en: 'ten thousand', }, 
        { ch: '十万', en: 'hundred thousand', }, 
        { ch: '一十万', en: 'one hundred thousand', }, 
        { ch: '百万', en: 'million', }, 
        { ch: '一百万', en: 'one million', }, 
        { ch: '千万/一千万', en: 'ten million', }, 
        { ch: '一千万', en: 'one million', }, 
        { ch: '亿', en: 'hundred million', },
        { ch: '一亿', en: 'one hundred million', },
        { ch: '十亿', en: 'billion', },
        { ch: '一十亿', en: 'one billion', },
        { ch: '百亿/一百亿', en: 'ten billion', },
        { ch: '千亿', en: 'hundred billion', },
        { ch: '一千亿', en: 'one hundred billion', },
        { ch: '兆', en: 'trillion', },
        { ch: '一兆', en: 'one trillion', },
        { ch: '十兆/一十兆', en: 'ten trillion', },
        { ch: '百兆', en: 'hundred trillion', },
        { ch: '一百兆', en: 'one hundred trillion', },
    ],
    // pronouns: [
    //     { ch: '我', en: 'me, I', },
    //     { ch: '你', en: 'you', }, 
    //     { ch: '您', en: 'you (polite)', }, 
    //     { ch: '他', en: 'he/him', }, 
    //     { ch: '她', en: 'she', }, 
    //     { ch: '我们', en: 'us', }, 
    //     { ch: '你们', en: 'you (plural)', }, 
    //     { ch: '您们', en: 'you (polite, plural)', }, 
    //     { ch: '他们', en: 'them (male)', }, 
    //     { ch: '她们', en: 'them (female)', }, 
    //     { ch: '我的', en: 'mine', }, 
    //     { ch: '你的', en: 'yours', }, 
    //     { ch: '您的', en: 'yours (polite)', }, 
    //     { ch: '他的', en: 'his', }, 
    //     { ch: '她的', en: 'her/hers', }, 
    //     { ch: '我们的', en: 'ours', }, 
    //     { ch: '你们的', en: 'yours (plural) ', }, 
    //     { ch: '您们的', en: 'yours (polite plural)', }, 
    //     { ch: '他们的', en: 'theirs (male)', }, 
    //     { ch: '她们的',  en: 'theirs (female)', }, 
    // ]
    // ,
    // family: [
    //     { ch: '家庭', en: 'family / household', }, 
    //     { ch: '父母', en: 'father and mother / parents', }, 
    //     { ch: '爸爸', en: 'father', }, 
    //     { ch: '父亲', en: 'father (formal)', },
    //     { ch: '妈妈', en: 'mother', }, 
    //     { ch: '母亲', en: 'mother (formal)', }, 
    //     { ch: '继母', en: 'step mother', }, 
    //     { ch: '哥哥', en: 'older brother', }, 
    //     { ch: '弟弟', en: 'younger brother', }, 
    //     { ch: '姐姐', en: 'older sister', }, 
    //     { ch: '妹妹', en: 'younger sister', },
    
    //     { ch: '配偶', en: 'spouse', }, 
    //     { ch: '先生', en: 'mister', }, 
    //     { ch: '丈夫', en: 'husband (formal)', }, 
    //     { ch: '老公', en: '(informal) husband', }, 
    //     { ch: '太太', en: 'missus', }, 
    //     { ch: '夫人', en: 'missus (old chinese)', }, 
    //     { ch: '妻子', en: 'wife (formal)', },
    //     { ch: '老婆', en: '(informal) wife', },
    
    //     { ch: '孩子', en: 'child'}, 
    //     { ch: '儿子', en: 'son'}, 
    //     { ch: '儿媳', en: 'son\'s wife'},
    //     { ch: '女婿', en: 'daughter\'s husband'},
    //     { ch: '女儿', en: 'daughter'}, 
    //     { ch: '叔叔', en: 'uncle (non-blood related)'},
    //     { ch: '爷爷', en: '(informal) father\'s father'}, 
    //     { ch: '奶奶', en: '(informal) father\'s mother'},
    //     { ch: '公公', en: '(informal) mother\'s father'},
    //     { ch: '姥姥', en: '(informal) mother\'s mother'}, 
    //     { ch: '祖父', en: 'father\'s father'}, 
    //     { ch: '祖母', en: 'father\'s mother'},
    //     { ch: '外祖父', en: 'mother\'s father'}, 
    //     { ch: '外祖母', en: 'mother\'s mother'},
    //     { ch: '岳父', en: 'father-in-law'}, // Check for distinction between wife and husband
    //     { ch: '岳母', en: 'mother-in-law'}, // Check for distinction between wife and husband
    //     { ch: '孙女', en: 'granddaughter'}, // Check for distinction between father's and mother's side
    //     { ch: '孙子', en: 'grandson'}, // Check for distincition between father's and mother's side
        
    //     // { ch: '外婆', en: '(informal) mother\'s mother'}, 
    //     // { ch: '外公', en: '(informal) mother\'s father'}, 
    //     // { ch: '亲戚', en: '(a) relative (i.e. family member)'}, 
    //     // { ch: '姑妈', en: 'aunt'},
    //     // { ch: '表兄弟', en: 'father\\'s sister\\'s sons / maternal male cousin'}, 
    //     // { ch: '世代', en: 'generation; generation to generation'}, 
    //     // { ch: '双胞胎', en: 'twin'}, 
    //     // { ch: '堂兄弟', en: 'father\\'s brother\\'s sons; paternal male cousin'}, 
    //     // { ch: '外甥', en: 'sister\\'s son / wife\\'s sibling\\'s son'}, 
    //     // { ch: '外甥女', en: 'sister\\'s daughter / wife\\'s sibling\\'s daughter'}, 
    //     // { ch: '兄弟', en: 'brothers / younger brother / brethren'}, 
    // ],
    // time: [
    //     // {ch: '时钟', en: 'clock', },
    //     // {ch: '闹钟', en: 'alarm clock', },
    //     // {ch: '电子报', en: 'digital clock', },
    //     // {ch: '古代', en: 'ancient history', },
    //     // {ch: '沙中', en: 'hourglass', },
    //     // {ch: '怀表', en: 'pocket watch', },
    //     // {ch: '日晷', en: 'sun dial', },
    //     {ch: '记事日历', en: 'schedule', },
    //     {ch: '休息', en: 'break', },
    //     {ch: '日历', en: 'calendar', },
    //     {ch: '世纪', en: 'century', },
    //     // {ch: '日期', en: 'date', },
    //     // {ch: '结束', en: 'end', },
    //     // {ch: '中世纪', en: 'middle ages', },
    //     // {ch: '早晨', en: 'early morning', },
    //     // {ch: '正点', en: 'punctiality', },
    //     // {ch: '时间', en: 'time', },
        
    //     {ch: '日出', en: 'sunrise', },
    //     {ch: '夕阳', en: 'sunset', },
    
    //     {ch: '历史', en: 'history', },
    //     {ch: '未来', en: 'future', },
    //     {ch: '现在', en: 'now', }, // Ask what is the difference between 目前 and 现在
    //     {ch: '过去', en: 'past', },
    
    //     // {ch: '早上', en: 'morning', },
    //     // {ch: '下午', en: 'afternoon', },
    //     // {ch: '晚上', en: 'evening/night', },
    //     // {ch: '黄昏', en: 'dusk', },
    //     // {ch: '黎明', en: 'dawn', },
        
    //     {ch: '前天', en: 'day before yesterday', },
    //     {ch: '昨天', en: 'yesterday', },
    //     {ch: '今天', en: 'today', },
    //     {ch: '明天', en: 'tomorrow', },
    //     {ch: '后天', en: 'day after tomorrow', },
    
    //     {ch: '季节', en: 'seasons', },
    //     {ch: '春天', en: 'spring', },
    //     {ch: '夏天', en: 'summer', },
    //     {ch: '秋天', en: 'autumn/fall', },
    //     {ch: '冬天', en: 'winter', },
        
    //     {ch: '年', en: 'year', },
    //     {ch: '月', en: 'month', },
    //     {ch: '天', en: 'day', },
    //     {ch: '小时', en: 'hour', },
    //     {ch: '分钟', en: 'minute', },
    //     {ch: '秒', en: 'second', },
    //     {ch: '毫秒', en: 'millisecond', },
    //     {ch: '点钟', en: 'oclock', },
    
    //     {ch: '周末', en: 'weekend', },
    //     {ch: '星期一', en: 'Monday', },
    //     {ch: '星期二', en: 'Tuesday', },
    //     {ch: '星期三', en: 'Wednesday', },
    //     {ch: '星期四', en: 'Thursday', },
    //     {ch: '星期五', en: 'Friday', },
    //     {ch: '星期六', en: 'Saturday', },
    //     {ch: '星期天', en: 'Sunday', },
        
    //     {ch: '一月', en: 'January', },
    //     {ch: '二月', en: 'Feburary', },
    //     {ch: '三月', en: 'March', },
    //     {ch: '四月', en: 'April', },
    //     {ch: '五月', en: 'May', },
    //     {ch: '六月', en: 'June', },
    //     {ch: '七月', en: 'July', },
    //     {ch: '八月', en: 'August', },
    //     {ch: '九月', en: 'September', },
    //     {ch: '十月', en: 'October', },
    //     {ch: '十一月', en: 'November', },
    //     {ch: '十二月', en: 'December', },
    // ],
    // color: [
    //     {ch: '颜色', en: 'color', },
    //     {ch: '白色', en: 'white', },
    //     {ch: '黑色', en: 'black', },
    //     {ch: '粉红色', en: 'pink', },
    //     {ch: '红色', en: 'red', },
    //     {ch: '蓝色', en: 'blue', },
    //     {ch: '绿色', en: 'green', },
    //     {ch: '黄色', en: 'yellow', },
    //     {ch: '紫色', en: 'purple', },
    //     {ch: '橙色', en: 'orange', },
    //     {ch: '棕色', en: 'brown', },
    //     {ch: '灰色', en: 'gray', },
    //     // {ch: '', en: 'gold', },
    //     // {ch: '', en: 'silver', },
    //     // {ch: '彩色', en: 'multicolor', },
    //     // {ch: '五颜六色', en: 'colorful', },
    //     // {ch: '莹', en: 'beautiful transparent color??', }, Confirm the meaning of this word
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    
    // ],
    // greetingsAndFarewells: [
    //     {ch: '你好', en: 'hello', },
    //     {ch: '您好', en: 'hello (polite)', },
    //     {ch: '你好吗', en: 'how are you?', },
    //     {ch: '您好吗', en: 'how are you? (polite)', },
    //     {ch: '拜拜', en: 'bye bye', },
    //     {ch: '再会', en: '[we will] hello again', },
    //     {ch: '明天见', en: 'see you tomorrow', },
    //     {ch: '喂', en: 'hey/hi (answering the phone)', },
    //     {ch: '再见', en: 'goodbye', },
    //     {ch: '早上好，你早，早', en: 'good morning', },
    //     {ch: '下午好', en: 'good afternoon', },
    //     {ch: '晚上好', en: 'good evening', },
    //     {ch: '晚安', en: 'good night', },
    //     {ch: '你怎么样', en: 'how is it going', },
    //     {ch: '你的周末怎么样', en: 'how was your weekend', },
    //     {ch: '回头见', en: 'see you soon', },
    //     {ch: '下个星期见', en: 'see you next week', },
    //     {ch: '改天再聊', en: 'talk to you later', },
    //     {ch: '慢走', en: 'take care', },
        
        
    // ],
    // people: [
    //     // {ch: '学者', en: 'scholar', },
    //     // {ch: '学生', en: 'student', },
    //     // {ch: '领导', en: 'leader', },
    //     // {ch: '男', en: 'male', },
    //     // {ch: '女', en: 'female', },
    //     // {ch: '男孩', en: 'boy', },
    //     // {ch: '女孩', en: 'girl', },
    //     // {ch: '朋友', en: 'friend', },
    //     // {ch: '人', en: 'people/person', },
    //     // {ch: '会员', en: 'member', },
    //     // {ch: '房东', en: 'landlord', },
    //     // {ch: '队友', en: 'teammate/parter', },
    //     // {ch: '服务员', en: 'Service Worker', },
    //     // {ch: '参加者', en: 'Attendee', },
    //     // {ch: '导师', en: 'tutor', },
    //     // {ch: '对手', en: 'opponent', },
    //     // {ch: '师傅', en: 'master', },
    //     // {ch: '士兵', en: 'soilder', },
    //     // {ch: '英雄', en: 'hero', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },

    // ],
    
    
    // jobs: [
    //     // {ch: '技术员', en: 'technician', },
    //     // {ch: '出纳员', en: 'cashier', },
    //     // {ch: '图书管理员', en: 'Librarian', },
    //     // {ch: '接待员', en: 'receptionist', },
    //     // {ch: '秘书', en: 'secretary', },
    //     // {ch: '电话推销员', en: 'Telemarketer', },
    //     // {ch: '推销员', en: 'saleman', },
    //     // {ch: '分析员', en: 'Analyst', },
    //     // {ch: '营销人员', en: 'Marketer', },
    //     // {ch: '工程师', en: 'engineer', },
    //     // {ch: '老师', en: 'teacher', },
    //     // {ch: '培训师', en: 'Trainer', },
    //     // {ch: '律师', en: 'lawyer', },
    //     // {ch: '治疗师', en: 'Therapist', },
    //     // {ch: '理发师', en: 'barber', },
    //     // {ch: '劳动者', en: 'laborer', },
    //     // {ch: '译者', en: 'translator', },
    //     // {ch: '历史学家', },
    //     // {ch: '地质学家', en: 'geologist', },
    //     // {ch: '艺术家', en: 'artist', },
    //     // {ch: '管家', en: 'housekeeper', },
    //     // {ch: '经纪人', en: 'broker', },
    //     // {ch: '主人', en: 'host (noun)', },
    //     // {ch: '广告文字撰稿人', en: 'copywriter', },
    //     // {ch: '机械', en: 'mechanic', },
    //     // {ch: '经理', en: 'manager', },
    //     // {ch: '人力资源', en: 'human resourses', },
    //     // {ch: '护士', en: 'nurse', },
    //     // {ch: '医生', en: 'doctor', },
    //     // {ch: '开发商', en: 'developer', },
    //     // {ch: '教练', en: 'coach', },
    //     // {ch: '算子', en: 'operator', },
    //     // {ch: '助理', en: 'assistant', },
    //     // {ch: '警官', en: 'police officer', },
    //     // {ch: '信使', en: 'mailman', },
    //     // {ch: '园丁', en: 'landscaper', },
    //     // {ch: '兽医', en: 'Veterinarian', },
    //     // {ch: '代客', en: 'valet', },
    //     // {ch: '编剧', en: 'Screenwriter', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },
    //     // {ch: '', en: '', },

    // ],
    // food: [],
    // school: [],
    // food: [],
    // animals: [],
    // weather: [],
    // sports: [],
    // tools: [],
    // vehicles: [],
    // furniture: [],
    // building: [],
    // electric: [],
    // plumbing: [],
    // clothes: [],
    // materials: [],
    // electronics: [],
    // verbs: [],
    // adjectives: [],
    // phrases: [],
    // office: [],
    // government: [],
    // geography: [],
    // medical: [],
}

for (let prop in answers) {
    for (let i = 0, length = answers[prop].length; i < length; i++) {
        answers[prop][i].audio = `
            <button type="button" onclick="document.querySelector('[src=\\'./english/${(() => answers[prop][i].en.replace(' ', '_'))()}.mp3\\']').play()">
                &#9654;
                <audio preload="none" src="./english/${(() => answers[prop][i].en.replace(' ', '_'))()}.mp3"></audio>
            </button>
        `
    }
}

// INDICATE MALE AND FEMALE AND FORMAL AND POLITE






